config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :tax_rates do
      post :import_tax_rates, on: :collection
      resources :taxable_zipcodes, shallow: true
    end
  end
end

app/views/spree/admin/shared/_import_tax_rates.html.erb
<div id="tax-rate-file-section">
  <%= form_tag import_tax_rates_admin_tax_rates_path, {:id => 'tax-rate-file-form', multipart: true}  do %>
    <label class="btn btn-success" for= "file-field">
      Import Tax Rates
    </label>
    <%= file_field_tag :tax_rates_file, id: 'tax-rate-file', accept: ".csv", id: "file-field"  %>
  <% end %>
</div>

app/views/spree/admin/tax_rates/_zipcodes.html.erb
<h4><%= "#{plural_resource_name(Spree::TaxRate)} ZipCodes" %></h4>
<table class="table">
  <thead>
    <tr>
      <th>
        <%= Spree.t(:tax_region_name) %>
      </th>
      <th>
        <%= Spree.t(:zip_code) %>
      </th>
      <th>
        <%= Spree.t(:amount) %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @tax_rate.taxable_zipcodes.each do |taxable|%>
      <tr>
        <td><%= taxable.region_name %></td>
        <td><%= taxable.zipcode %></td>
        <td><%= taxable.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/taxable_zipcodes/index.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:tax_rates), spree.admin_tax_rates_url %> /
  <%= "#{@tax_rate.name}'s ZipCodes" %>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th>
        <%= Spree.t(:tax_region_name) %>
      </th>
      <th>
        <%= Spree.t(:zip_code) %>
      </th>
      <th>
        <%= Spree.t(:amount) %>
      </th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @tax_rate.taxable_zipcodes.each do |taxable|%>
      <tr>
        <td><%= taxable.region_name %></td>
        <td><%= taxable.zipcode %></td>
        <td><%= taxable.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>